version: "3"
services:
  solr:
    image: solr
    ports:
      - "8983:8983"
    networks: [search]
    environment:
      ZK_HOST: "zoo:2181"
    depends_on: [zoo]
    volumes:
      - ./.data/solr:/var/solr

  zoo:
    image: zookeeper:3.9
    networks: [search]
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok"

networks:
  search:
    driver: bridge
