version: "3"
services:
  search:
    image: getmeili/meilisearch:latest
    ports:
      - 7700:7700
    volumes:
      - ./.data/meili:/meili_data
    entrypoint:
      - meilisearch
    command:
      - --master-key
      - xWMHVnYwrZjr8IkkdrjmnpaFw10_w_78PlfcUOsnlB0
